### ISSUE TITLE
Update Tutor FE to store highlights in new endpoint

### ISSUE THREAD

**Issue by BruceP99166** [openstax/tutor#210]
# Description
As a developer I want a Tutor endpoint for highlights so that they can be used to select assessments.

# Acceptance
- Highlighting works just as it did before and the user experience is unchanged

### Distilled Acceptance Tests
Given,
If,
Then,

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- ~If UX design is needed then the UX label is added~
- ~f UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.~
- ~A high-level solution (development approach for the code change) is added to the issue~
- ~If prototype code is generated, it is linked to the issue.~
- ~If tech briefs are generated, they are linked to the issue.~

1B-DECOMP
  - [x] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [x] Estimate is updated for the work item issues.
  - [x] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [x] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - ~The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.~
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [ ] The solution is updated.

2A-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by brittany-johnson** [comment]
Successfully highlighted, added notes, and deleted highlights these elements: 
- Tables
- Learning objectives
-MathJax in a paragraph 
- Text in a paragraph 
- (Sometimes takes a few tries) an 'equation and 'os-equation-number` Physics 1.3 'Percent Uncertainty' 
- Notes and titles of notes
- `problems` in notes 
- Images and their captions

Unsuccessful: 
- Numbered section header (Example: Physics '1.3 Accuracy, Precision, and Significant Figures')
- Highlighting from top to bottom and image to 2 paragraphs. Works if you highlight starting with the 2nd paragraph up to the image.  (Physics Figure 1.23 to text 'then the measurements would not be very precise because there would be significant variation from one measurement to another.'
- Highlighting (example:)Physics Figure 1.24 caption from the last word to first
- The letters on a list-style alpha

**Comment by Malar-Natarajan** [comment]
Tested in QA:
https://tutor-qa.openstax.org/book/342#import-auto-id3190423. student10

1. View in book" icon in the Highlights summary page is not working
2. There is a change in the order of sections displayed in Highlights summary page
3. Some section headings are displaying spans
4. took screenshots yesterday of few highlight summary pages and this one was one of them. I am not seeing few sections for this student08. I might have wrongly saved the student name but the sec 1.5 highlight is exactly matching. So I am assuming remaining highlights are missing.

**Comment by Malar-Natarajan** [comment]
@nathanstitt Retested in QA with updated SHA and below issues found:

Issues while testing the migration of highlight storage. I took screenshots of few highlights before code freeze and looking at the same spot now:

1. Spans still displayed in the dropdown list for certain sections that were highlighted before changing highlight storage

2. Order of highlights displayed in Summary page is incorrect - supposed to be ordered by section numbers

3. Two Section numbers displayed for or certain sections that were highlighted before changing highlight storage

4. Few highlights that I made before code freeze are still missing in student08

5. Format mismatch in one highlight (see first screenshot below in 11.5 11.4 section near the link)

6. Chapter objectives are not formatted well in the Highlights summary page

**Comment by Malar-Natarajan** [comment]
1, 2, 3, 5, 6 are fixed and looks good.

4 - The reference view is not loaded by course, instead
it’s by ecosystem. However a student may be in multiple
courses that refer to the same ecosystem.

When the view needs to load things for the users course it
looks at all the available courses.  it first tries to find
an active one, and then just the first match.

This affects things like notes that are linked to courses.
If a student is in only one course then all’s well but if
they’re in multiple courses that are active it’s hit-or-miss

Since in production students are in only one active course this issue will not happen.
IN staging tested bio & socio with single active course and looks good
