### ISSUE TITLE
Student's course average not updating when accepting/rejecting late work

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#294]
### Description
Description

A student course average isn't updating when accepting or rejecting late work; homework/reading average and progress update as does the course average.

https://drive.google.com/file/d/1QzehcZ2Q9SJ8Lsoq84US9BKGsPQKNA5O/view?usp=sharing

**To Reproduce**
Steps to reproduce the behavior are
1. Go to a teacher's course scores page
2. Accept or reject late work

**Expected behavior**
the student's course average updates when late work is accepted or rejected

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Firefox

**Smartphone (please complete the following information):**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [x] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment]
this was fixed in https://github.com/openstax/tutor-js/pull/2544 but I failed to link it before it was merged

**Comment by Brooke-Fail** [comment]
@nathanstitt 
This issue is no longer occurring for older late works. However, the following issues happen for new late work. The overall and student course percentage are not updating immediately after accepting late work or using the old score. The percentages update upon a page refresh though. Also an error pops up now every time you click Accept late score or Use this score. The user can still progress if they click OK on the error.

Screenshot of Error:
![Screen Shot 2019-03-18 at 3.28.13 PM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/9a831dbd-ad88-4c59-a0e8-8a4696f76d3a)

Link to Video:
https://drive.google.com/open?id=1glcQ96ENYTLg8gzk2bnX7jd82MtxeAUZ

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in staging.
