### ISSUE TITLE
Give pilot teachers link(s) to monthly analytics

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/tutor#338]
### Description
As an OpenStax Tutor AP pilot teacher, I want an easy way to link from my Tutor course to my RAD dashboard, so that I can look at extra analytics without digging through my email to find the right link.

URL is: analytics.openstax.org 
Button/Menu name is: Research analytics

The menu link should show up under Performance Forecast in the main menu.

### Acceptance Criteria
- RAD dashboard link ONLY shows up for AP Physics and AP Bio courses
(we only have pilot teachers using these course currently, so it's okay to show up for all, but _could we_ limit to certain courses, if we wanted to?)
- The menu link should show up under Performance Forecast in the main menu.

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete
- [x] If UX design is needed then the UX label is added
- [x] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue
- ~A development approach for the code change, prototype code, or tech brief is done and added to the issue~

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [x] Release is selected

1C-DESIGN
- [x] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
  

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by carlycurran** [comment]
@dkhowala @nathanstitt 

I'm thinking the best and easiest way to achieve this is through a menu item that links to the RAD dashboard, but I am totally open to suggestions from you two.

**Comment by nathanstitt** [comment]
yes that's what I'd envisioned as well

**Comment by dkhowala** [comment]
Can we add extra menu items for only a few selected users?

**Comment by nathanstitt** [comment]
@dkhowala yes, we can do that

**Comment by dkhowala** [comment]
![Screen Shot 2019-05-15 at 2.23.26 PM.png](https://images.zenhubusercontent.com/5c12c502ea8fd844ba2fce8c/d7e80a33-ae78-4d52-9e3b-3bce5e29c82f)

This is one point where we can link to the RAD dashboard. 

Since this is so layered, we can show it on the performance analytics page since they are somewhat connected. thought? @carlycurran @nathanstitt 

![Screen Shot 2019-05-15 at 2.22.44 PM.png](https://images.zenhubusercontent.com/5c12c502ea8fd844ba2fce8c/49591097-76d5-4cb6-af73-9377e02577d1)

**Comment by carlycurran** [comment]
I like the idea of making this as easy for us as possible. There is a lot already in the menu bar, so I'm interested in what y'all think of that. @dkhowala is that what you mean by "so layered"? 

I agree it makes sense to send them to the RAD dash from the PF page, but could we put the button at the top, maybe next to the Dashboard button? Since it will be one RAD page/teacher (not section) and the button could be called "Research analytics" with a little pop-out icon thingy? Is that too confusing?

**Comment by nathanstitt** [comment]
I kinda like the idea of having the link in both the PF beside the "Back.." btn and also in the menu.

I agree it's natural to link from the Performance Forecast, but I don't think we should force them to visit it just to get to the stats.  If we also have it in the menu that will give them access from anywhere in Tutor.

**Comment by dkhowala** [comment]
I think I agree with both of you and that we should have the link in both the places
1. Next to 'Back to Dashboard' button in PF. (If it is one RAD page/teacher than the top level makes more sense.)
2. In the menu items below PF. ( Users shouldn't have to necessarily go to the PF to find this link.)

What are we calling this button/link? Debshilla with check with marketing and get back to us on this.

**Comment by carlycurran** [comment]
@dkhowala your lo-fi is beautiful, so I checked that box and am moving this to Decomp :)

**Comment by dkhowala** [comment]
:). Awesome. let me know if I need to do any specs or any other work on this.

**Comment by carlycurran** [comment]
Carly needs to get name and URL for this

**Comment by carlycurran** [comment]
@nathanstitt -- Just peeked at QA. Looks like the menu link to "Research analytics" shows up in APUSH, too. 

Is there a way to make this _only_ show up for AP Bio and AP Physics?

Also, I thought we were going to add this button to Performance Forecast page, too. I don't see it there, but may be because I only have one student in this class.

**Comment by Brooke-Fail** [comment]
The Research Analysis link is currently in the main menu drop down above Manage Payments. The link works, however, everyone has access to the link.  Students, unverified faculty, and accounts that don't have any AP courses can access the link for the same main menu.

Card for this issue is:
https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/495

**Comment by Brooke-Fail** [comment]
The research Analytics link is correctly under the Performance Forecast. Verified in QA (again).

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
