### ISSUE TITLE
AP Bio - get the number of questions tagged to each chapter

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#380]
### Description
AP Bio - get the number of questions tagged to each chapter

This is a follow-on to the original request for AP Physics: https://app.zenhub.com/workspaces/openstax-tutor-560aef617a763234615d6a0f/issues/openstax/tutor/316

### Acceptance Criteria
This work, but or AP Bio, plz: 
https://docs.google.com/spreadsheets/d/1I8dlXKumOawaYBoIJdtQGlW6qLBTgrNNx_DdC342HCc/edit#gid=325139612

### Checklist for Done
1A-DEFINE
- [x] Description is complete

**Comment by openstaxalina** [comment]
@carlycurran @Dantemss this work is no longer needed, since we discovered that there **are** plenty of AP Bio assesments tagged with APLOs, they are just tagged to the wrong module UUIDs.

I created a new card for the module UUIDs work that we do need instead: https://github.com/openstax/tutor/issues/389

Apologies for the confusion.
