### ISSUE TITLE
Bug: Preview courses are not displaying performance forecast for bio & physics

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#40]
**SCENARIO** _Preview courses are not displaying performance forecast for bio & physics.
Sociology displays the performance forecast.
Refer video

Issue identified by Carly during regression testing.

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **Product:**
` [ ] ` Accounts ` [ ] ` BigLearn
` [ ] ` Exercises ` [ ] ` CNX
` [ ] ` Payments  ` [X] ` Tutor
` [ ] ` Highlight ` [ ] ` Web
- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [X] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [X] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [X] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by nathanstitt** [comment]
@Dantemss mentioned that this is probably because BL was not responding quickly enough when the preview courses were built.

To test I created a new course offering for bio2e on tutor-demo, and then logged in as a teacher and viewed the new "bio2e" preview.  It's performance forecast showed plenty of activity.

To correct any previews that don't show correctly, we'll have to mark the offering as "Not available for teachers", and then create a new offering.  Once that's done the performance report should be correct.

**Comment by nathanstitt** [comment]
I tested as teacher01 on tutor-demo and all the preview courses have good performance forecasts
