### ISSUE TITLE
APUSH: Set Tutor captions to Roman

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#475]
### Description
As an OpenStax Tutor user (in particular, a History teacher), I want to see certain names in italics, so that my students are using a product where grammar rules are followed.

### Acceptance Criteria
Table, image and other captions appear in roman style, and the markup for italics works. 

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [ ] Acceptance criteria are complete

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [x] Release is selected

1C-DESIGN
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.

**Comment by nathanstitt** [comment]
@carlycurran & @openstaxalina 

I see that captions are currently using the same font as the other content, `HelveticaNeue`, but they are all set to italic, this prevents items that are set to one Italic from standing out because the entire caption is italic.  

They currently look like:
![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/8dc68d55-fc8c-407f-9521-78640fa3775a)

A few questions:

Do we want to change the font to roman, or just remove the italicizing from them and leave as HelveticaNeue? Doing so will make them look like:
![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/3a830d67-5819-475c-8f27-57cb224a6d7e)

Or we can switch to our standard serif font stack which is ` 'Merriweather', Georgia, Times, serif;`. That will look like:
![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/4d12d7fb-3f7d-41d2-ad55-525c0a03bd05)

Or if we really really want "Times New Roman" font it'll be:
![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/01afbd0c-c3ed-470d-a421-9f4d98f2ff7a)

**Comment by openstaxalina** [comment]
@nathanstitt thank you for describing these options for us!

I wonder if by "Roman", @carlycurran meant "non-italic" rather than "Times New Roman"?  

Anyway, from my perspective any of the options would work, because it would achieve the goal that italics can be identified.  So I will defer to @dkhowala and @carlycurran on this.  Perhaps @dkhowala could determine the best path and then confirm with Carly when she is back.

**Comment by dkhowala** [comment]
@openstaxalina, you're right. Roman refers to regular (non-italic) font styling rather than the font 'Times new roman'. Let's not change the font and keep it Helvetica Neue across.

Within captions, do we have any code that can identify the stuff that needs to be italicized? If yes, then we need to apply the italicized style to only those and not the entire caption.

**Comment by openstaxalina** [comment]
Yes, the content that needs to be italicized will have tags around it.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
