### ISSUE TITLE
Improve response validator algorithm 

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#584]
### Description
Improvements to response validator algorithm. 

### Acceptance Criteria
The biggest things that we will want to test are that:

1) Using any real words should produce a "valid" response
2) Spelling correction should be on and simple mistyping of words should not make an otherwise valid response invalid. As an example: "This is my response" and "This is my respone" should both be ok. Spelling correction is only done on words at least 5 characters long, and corrections must be within an edit distance of 3 to be corrected. Long strings of garbage should fail for the most part, and short misspelled words shouldn't be corrected.
2) For questions requiring math (mainly physics), any response with math symbols or numbers present should produce a "valid" response
3) For questions that don't require math (lots of biology, sociology), entering numbers or math symbols alone shouldn't produce a valid response

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.

**Comment by reedstrm** [comment]
@aew2 want to drop some description here? So @Brooke-Fail knows what to expect on testing?

**Comment by aew2** [comment]
The biggest things that we will want to test are that:

1) Using any real words should produce a "valid" response
2) Spelling correction should be on and simple mistyping of words should not make an otherwise valid response invalid.  As an example: "This is my response" and "This is my respone" should both be ok.  Spelling correction is only done on words at least 5 characters long, and corrections must be within an edit distance of 3 to be corrected.  Long strings of garbage should fail for the most part, and short misspelled words shouldn't be corrected.
2) For questions requiring math (mainly physics), any response with math symbols or numbers present should produce a "valid" response
3) For questions that don't require math (lots of biology, sociology), entering numbers or math symbols alone shouldn't produce a valid response

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.
