### ISSUE TITLE
APUSH: Table header row design

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/tutor#610]
GLOBAL
Tutor APUSH
https://tutor-content.openstax.org/course/88

Header row of tables should have design treatment applied to distinguish it from standard content rows. If you'd like us to achieve this with mark up, applying bold tags to header row treatment, just confirm for us and we could apply that globally.

![table header row design_APUSH](https://user-images.githubusercontent.com/19212926/65351215-7f21dd00-dbb5-11e9-8b4b-9524c1091195.JPG)

**Comment by carlycurran** [comment]
@openstaxalina, on our APUSH tracker, it says this is addressed with markup. Is that the case?

**Comment by openstaxalina** [comment]
Since the header row is also undifferentiated on CNX, I think that this table header row is not properly marked up: https://content05.cnx.org/contents/CmIfJ6vh@38.2:ati9GAKm@14/2-2-%F0%9F%93%96-Chapter-2-Introductory-Essay-1607-1763

@oscryan would you be able to look at the markup and provide instructions here (and a tagging legend update, if needed) to have proper header rows?

![Screen Shot 2019-10-07 at 3 21 08 PM](https://user-images.githubusercontent.com/7863733/66345737-3ccb0080-e916-11e9-9c34-8abec7fe682d.png)

**Comment by mwest-WWprod** [comment]
@openstaxalina @carlycurran Yes, to confirm I believe the header rows were not tagged as such and that's why they appear the way they do. If it does entail a tagging legend update we will keep an eye out for that, but as of now our team is going through and applying the normal header row treatment as we have in past books. The lack of treatment was originally due to a miscommunication in our manuscript.

**Comment by oscryan** [comment]
Yes, it is not marked as a header row. Header rows should be in `<thead>` tags, not `<tbody>`. Table header rows are addressed in row 25 of the tagging legend.

**Comment by openstaxalina** [comment]
@mwest-WWprod and @oscryan that is good news that this is an easy fix -- thank you for the updates!  I am closing this issue.
