### ISSUE TITLE
APUSH: Differing table styling in Primary Sources

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/tutor#615]
GLOBAL
Tutor APUSH
https://tutor-content.openstax.org/book/88

We're seeing some differing table styling in a couple chapters, see below for examples from Primary Sources. Let us know if there is any mark up changed entailed here. Note that it also appears as though font sizing differs between tables 

**Table Styling**
From 2.26
![TableAppearance_2 26_APUSH](https://user-images.githubusercontent.com/19212926/65557283-c9ca8e80-df00-11e9-974d-e311c86b6d60.JPG)

From 3.27
![TableAppearance_3 27_APUSH](https://user-images.githubusercontent.com/19212926/65557346-ff6f7780-df00-11e9-80f2-d8f3d885e5d7.JPG)
. 
**Font** (screenshots taken at same zoom level)
From 1.16
![TableAppearance_1 16_APUSH](https://user-images.githubusercontent.com/19212926/65558092-786fce80-df03-11e9-9a4f-088e2eeaeb21.JPG)

From 2.21
![TableAppearance_2 21_APUSH](https://user-images.githubusercontent.com/19212926/65558108-832a6380-df03-11e9-8363-0b57b0d2d35b.JPG)

**Comment by oscryan** [comment]
This is a markup issue. The 2.26 example has the header row marked up in a <thead> tag, and the 3.27 example just has it in a normal row. I'm not sure I see the font size change.

**Comment by openstaxalina** [comment]
Side-by-side showing the font discrepancy:
URL on the left is https://tutor-content.openstax.org/book/88/page/93682
URL on the right is https://tutor-content.openstax.org/book/88/page/93709
![Screen Shot 2019-09-26 at 4 29 59 PM](https://user-images.githubusercontent.com/7863733/65726532-ebe81c00-e07a-11e9-98a1-9184c7eabbce.png)

Same content on content05:
left: https://content05.cnx.org/contents/CmIfJ6vh@35.32:jLHNsWMl@9/1-16-%E2%9C%92%EF%B8%8F-The-Oral-Tradition-of-the-Foundation-of-the-Iroquois-Confederacy
right: https://content05.cnx.org/contents/CmIfJ6vh@35.32:oCrwsbz8@5/2-21-%E2%9C%92%EF%B8%8F-A-City-Upon-a-Hill-Winthrop-s-Modell-of-Christian-Charity-1630

@carlycurran is checking with @nathanstitt about whether we Tutor does relative font sizing for tables in Tutor.

**Comment by nathanstitt** [comment]
@carlycurran @openstaxalina - after investigating the difference in font size is due to the larger font being enclosed in a `p` tag.

For unknown reasons, we have a rule that sets `p` tags that are inside a `table` or `ul` to be 17.5px.

I don't see any real reason for that rule, so I'm going to remove it unless anyone thinks differently.  

This is what it looks like at the larger 17.5px:
![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/aff29c54-b160-43e2-91e0-e2513fc7810b)


And this is what it looks like with the rule removed and the font being the regular 14px size:
![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/c031e15d-0cba-4f9a-8776-977cb773aff9)

**Comment by openstaxalina** [comment]
Thank you for tracking this down, Nathan!  I agree with removing the rule.  We may use < p > when there are multiple paragraphs in a cell, but we would be using it to add padding between paragraphs, not expecting the different font size.  So removing the rule would be helpful from my perspective.

**Comment by nathanstitt** [comment]
@carlycurran & @openstaxalina  I'm sorry but I typed too soon.  

When I went to remove the rule I discovered that what we're really doing is setting all text inside a `p` tag to be 17.5, which explains why the larger font is styled that way.  Almost all of the content in the book is inside a `p` tag and is also 17.5 due to that rule.   

The smaller text is not inside a `p` tag so it is defaulting to the standard Tutor font size of 14px.

17.5 is a strange size.  I'd recommend we split the difference and set all font inside the reference view to 16px.

Here's what is now larger with some of the surrounding content:
![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/27ed5fb4-b3af-4e97-b298-f478c742e37b)



And here's the other example of the non `p` enclosed text:
![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/8e2cab1b-8ca6-4956-9933-ddfc504a3b79)

**Comment by openstaxalina** [comment]
Thank you for the update, Nathan!
@carlycurran I'll add this to tomorrow's agenda w/ WW to discuss the proposed solution(s).

**Comment by carlycurran** [comment]
interesting! okay, tomorrow with Devika, let's take a look at what's impacted if we make a font size change like that. Thank you, @nathanstitt for digging into this!

**Comment by carlycurran** [comment]
We are good to go on making this font change! Let's move it all to 16

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
